//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Concrete.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WhatWasReadContext : DbContext
    {
        public WhatWasReadContext()
            : base("name=WhatWasReadContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Filter> Filters { get; set; }
        public virtual DbSet<FilterTarget> FilterTargets { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<BooksWithAuthor> BooksWithAuthors { get; set; }
    }
}
