//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Concrete.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterTarget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilterTarget()
        {
            this.Filters = new HashSet<Filter>();
        }
    
        public int FilterTargetId { get; set; }
        public string FilterTargetName { get; set; }
        public string FilterTargetSchema { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string FilterName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filter> Filters { get; set; }
    }
}
