//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Concrete.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public int FilterId { get; set; }
        public int FilterTargetId { get; set; }
        public string FilterColumnName { get; set; }
        public string QueryWord { get; set; }
        public string Comparator { get; set; }
        public string FilterName { get; set; }
    
        public virtual FilterTarget FilterTarget { get; set; }
    }
}
